config/routes.rb
Brasol::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.prepend do
    devise_scope :user do
      post '/user/seen_reg_page', to: "user_registrations#seen_reg_page", as: :seen_reg_page
    end
  end

end

app/models/spree/address.rb
module Spree
  class Address < ActiveRecord::Base
    belongs_to :country
    belongs_to :state

    has_many :shipments

    validates :firstname, :lastname, :address1, :city, :country, :phone, :presence => true
    validate :state_validate

    attr_accessible :firstname, :lastname, :address1, :address2,
                    :city, :zipcode, :country_id, :state_id,
                    :country, :state, :phone, :state_name,
                    :company, :alternative_phone

    # Disconnected since there's no code to display error messages yet OR matching client-side validation
    def phone_validate
      return if phone.blank?
      n_digits = phone.scan(/[0-9]/).size
      valid_chars = (phone =~ /^[-+()\/\s\d]+$/)
      errors.add :phone, :invalid unless (n_digits > 5 && valid_chars)
    end

    def self.default
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new({:country => country}, :without_protection => true)
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.try(:abbr) || state.try(:name) || state_name
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at', 'order_id') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
          :name => full_name,
          :address1 => address1,
          :address2 => address2,
          :city => city,
          :state => state_text,
          :zip => zipcode,
          :country => country.try(:iso),
          :phone => phone
      }
    end

    private

    def state_validate
      # Skip state validation without country (also required)
      # or when disabled by preference
      return if country.blank? || !Spree::Config[:address_requires_state]

      # ensure associated state belongs to country
      if state.present?
        if state.country == country
          self.state_name = nil #not required as we have a valid state and country combo
        else
          if state_name.present?
            self.state = nil
          else
            errors.add(:state, :invalid)
          end
        end
      end

      # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
      if state_name.present?
        if country.states.present?
          states = country.states.find_all_by_name_or_abbr(state_name)

          if states.size == 1
            self.state = states.first
            self.state_name = nil
          else
            errors.add(:state, :invalid)
          end
        end
      end

      # ensure at least one state field is populated
      errors.add :state, :blank if state.blank? && state_name.blank?
    end

  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

  attr_accessible :new_user_email, :new_user_password
  attr_accessor :new_user_email, :new_user_password

  def deliver_order_confirmation_email
    begin
      Spree::OrderMailer.delay.confirm_email(self)
    rescue Exception => e
      logger.error("#{e.class.name}: #{e.message}")
      logger.error(e.backtrace * "\n")
    end
  end

  def new_user_email=(email)
    self.email = email
  end

end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do

  def applicable_filters
    fs = []
    fs << Spree::ProductFilters.taxons_below(self)
    ## unless it's a root taxon? left open for demo purposes

    fs << Spree::ProductFilters.price_filter if Spree::ProductFilters.respond_to?(:price_filter)
    fs << Spree::ProductFilters.brand_filter if Spree::ProductFilters.respond_to?(:brand_filter)
    fs
  end

end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  attr_accessible :firstname, :lastname
end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do

  def update
    if @order.update_attributes(object_params) and @order.errors.empty?
      create_and_associate_user

      if @order.errors.present?
        respond_with(@order) { |format| format.html { render :edit } } and return
      end

      fire_event('spree.checkout.update')
      unless apply_coupon_code
        respond_with(@order) { |format| format.html { render :edit } }
        return
      end

      if @order.next
        state_callback(:after)
      else
        flash[:error] = t(:payment_processing_failed)
        respond_with(@order, :location => checkout_state_path(@order.state))
        return
      end

      if @order.state == 'complete' || @order.completed?
        flash.notice = t(:order_processed_successfully)
        flash[:commerce_tracking] = 'nothing special'
        respond_with(@order, :location => completion_route)
      else
        respond_with(@order, :location => checkout_state_path(@order.state))
      end
    else
      respond_with(@order) { |format| format.html { render :edit } }
    end
  end

  def before_address
    if @order.user
      unless @order.bill_address
        @order.bill_address ||= @order.user.bill_address || Spree::Address.default
      end
      unless @order.ship_address
        @order.ship_address ||= @order.user.ship_address || Spree::Address.default
      end
    else
      @order.bill_address = Spree::Address.default unless @order.ship_address
      @order.ship_address = Spree::Address.default unless @order.ship_address
    end

    if @order.user
      @order.bill_address.firstname = @order.user.firstname if @order.user.firstname.present?
      @order.bill_address.lastname = @order.user.lastname if @order.user.lastname.present?
    end
  end

  def create_and_associate_user
    return if (not @order.state == "address") || current_user

    existing_user = Spree::User.find_by_email(params[:order][:new_user_email])
    if existing_user && existing_user.valid_password?(params[:order][:new_user_password])
      sign_in existing_user
      return
    end

    user = Spree::User.new(email: params[:order][:new_user_email], password: params[:order][:new_user_password],
                           password_confirmation: params[:order][:new_user_password])
    if user.save
      sign_in user
      @order.associate_user! user
    else
      user.errors.each { |key, message| @order.errors.add(key, message) }
    end
  end

  def after_complete
    if @order.user
      @order.user.update_attribute(:bill_address, @order.bill_address) # Update last billing address used.
      @order.user.update_attribute(:ship_address, (@order.bill_address == @order.ship_address ? nil : @order.ship_address)) # Update last shipping address used.
      @order.user.update_attribute(:firstname, @order.bill_address.firstname)
      @order.user.update_attribute(:lastname, @order.bill_address.lastname)
    end

    session[:order_id] = nil
  end

  def check_registration
    return if session[:seen_reg_page]
    return if spree_current_user or current_order.email
    store_location
    redirect_to spree.checkout_registration_path
  end

end

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @products = {}

      Spree::Taxonomy.includes(:root => :children).each do |taxonomy|
        view_context.bottom_level_taxons(taxonomy.root).each do |t|
          base_scope = Spree::Product.active
          base_scope = base_scope.in_taxon(t)
          base_scope = base_scope.on_hand unless Spree::Config[:show_zero_stock_products]
          @products[t] = base_scope.includes([:master => :prices]).limit(4)
        end
      end
    end

  end
end

app/controllers/spree/orders_controller_decorator.rb
# from spree_minicart
module Spree
  OrdersController.class_eval do

    respond_to :js, :only => [:populate, :update]

    ssl_allowed :populate, :update

  end
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do
  before_filter :define_2d_option_matrix, :only => :show

  def define_2d_option_matrix
    variants = Spree::Config[:show_zero_stock_products] ?
        @product.variants.active.select { |a| !a.option_values.empty? } :
        @product.variants.active.select { |a| !a.option_values.empty? && a.in_stock }

    return if variants.empty?

    if @product.option_types.select { |a| a.name.start_with? 'size' }.empty? &&
        @product.option_types.select { |a| a.name.start_with? 'color' }.empty?
      @other_variants_present = true
      return
    end

    variant_ids = {}
    sizes = []
    colors = []
    variants.each do |variant|
      active_size = variant.option_values.select { |a| a.option_type.name.start_with? 'size' }.first
      active_color = variant.option_values.select { |a| a.option_type.name.start_with? 'color' }.first

      if active_color.present? and active_size.present?
        variant_ids[active_size.id.to_s + '_' + active_color.id.to_s] =
            {variant_id: variant.id, color_id: active_color.id, size_id: active_size.id}
      elsif active_color.present?
        variant_ids[active_color.id.to_s] = {variant_id: variant.id, color_id: active_color.id}
      elsif active_size.present?
        variant_ids[active_size.id.to_s] = {variant_id: variant.id, size_id: active_size.id}
      end

      sizes << active_size unless active_size.nil?
      colors << active_color unless active_color.nil?
    end
    size_sort = Hash['S', 0, 'M', 1, 'L', 2, 'XL', 3]
    @double_option = {'sizes' => sizes.sort_by { |s| size_sort[s.presentation] || 0 }.uniq,
                      'colors' => colors.uniq,
                      'variant_ids' => variant_ids}
  end

  def show
    return unless @product

    @variants = Spree::Variant.active.includes([:option_values, :images]).where(:product_id => @product.id)
    @product_properties = Spree::ProductProperty.includes(:property).where(:product_id => @product.id)

    referer = request.env['HTTP_REFERER']
    if referer
      referer_path = URI.parse(request.env['HTTP_REFERER']).path
      referer_path = URI.decode(referer_path)
      if referer_path && referer_path.match(/\/t\/(.*)/)
        @taxon = Spree::Taxon.find_by_permalink($1)
      end
    end

    if @product.taxons.present?
      base_scope = Spree::Product.active
      base_scope = base_scope.in_taxon(@product.taxons[0])
      base_scope = base_scope.on_hand unless Spree::Config[:show_zero_stock_products]
      @similar_products = base_scope.includes([:master => :prices]).limit(5)
    end
    @similar_products.reject! { |p| p.id == @product.id }

    respond_with(@product)
  end

end

app/controllers/spree/user_registrations_controller_decorator.rb
Spree::UserRegistrationsController.class_eval do

  def seen_reg_page
    session[:seen_reg_page] = true
    redirect_to checkout_state_path("address")
  end

end

app/helpers/spree/base_helper_decorator.rb
Spree::BaseHelper.class_eval do
  def ukraine
    Spree::Country.find_by_id(211)
  end

  def get_taxonomies
    @taxonomies ||= Spree::Taxonomy.includes(:root => :children)
  end

  def bottom_level_taxons(root_taxon)
    return [root_taxon] if root_taxon.children.empty?
    root_taxon.children.map do |taxon|
      bottom_level_taxons(taxon)
    end.flatten
  end

  # from spree_minicart
  # removed current_page? check because link_to_cart is called everywhere by spree_minicart
  def link_to_cart(text = nil)
    text = text ? h(text) : t('cart')
    css_class = nil

    if current_order.nil? or current_order.line_items.empty?
      text = "#{text}: (#{t('empty')})"
      css_class = 'empty'
    else
      text = "#{text}: (#{current_order.item_count})  <span class='amount'>#{current_order.display_total}</span>".html_safe
      css_class = 'full'
    end

    link_to text, cart_path, :class => css_class
  end
end

app/views/spree/checkout/_address.html.erb
<div class="columns alpha six" data-hook="billing_fieldset_wrapper">
  <fieldset id="billing" data-hook>
    <legend><%= t(:billing_address) %></legend>
    <% unless current_user %>
      <p class="field" id="bemail">
        <%= form.label :new_user_email, t(:email) %><span class="required">*</span><br/>
        <%= form.text_field :new_user_email, :class => 'required' %>
      </p>

      <p class="field" id="bfirstname">
        <%= form.label :new_user_password, t(:password) %><span class="required">*</span><br/>
        <%= form.password_field :new_user_password, :class => 'required' %>
      </p>
    <% end %>
    <%= form.fields_for :bill_address do |bill_form| %>
        <div class="inner" data-hook="billing_inner">
          <p class="field <%= 'noTopField' if current_user %>" id="bfirstname">
            <%= bill_form.label :firstname, t(:first_name) %><span class="required">*</span><br />
            <%= bill_form.text_field :firstname, :class => 'required' %>
          </p>
          <p class="field" id="blastname">
            <%= bill_form.label :lastname, t(:last_name) %><span class="required">*</span><br />
            <%= bill_form.text_field :lastname, :class => 'required' %>
          </p>
          <% if Spree::Config[:company] %>
              <p class="field" id="bcompany">
                <%= bill_form.label :company, t(:company) %><br />
                <%= bill_form.text_field :company %>
              </p>
          <% end %>
          <p class="field" id="bcity">
            <%= bill_form.label :city, t(:city) %><span class="required">*</span><br />
            <%= bill_form.text_field :city, :class => 'required' %>
          </p>
          <p class="field" id="baddress1">
            <%= bill_form.label :address1, t(:street_address_exp) %><span class="required">*</span><br />
            <%= bill_form.text_field :address1, :class => 'required' %>
          </p>
          <p class="field" id="baddress2">
            <%= bill_form.label :address2, t(:street_address_2) %><br />
            <%= bill_form.text_field :address2 %>
          </p>
          <p class="field" id="bcountry">
            <%= bill_form.label :country_id, t(:country) %><span class="required">*</span><br />
        <span id="bcountry">
          <%= bill_form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'required'} %>
        </span>
          </p>

          <% if Spree::Config[:address_requires_state] %>
              <p class="field" id="bstate">
                <% have_states = !@order.bill_address.country.states.empty? %>
                <%= bill_form.label :state, t(:state) %><span class="required">*</span><br />
                <% state_elements = [
                        bill_form.collection_select(:state_id, @order.bill_address.country.states,
                                                    :id, :name,
                                                    {:include_blank => true},
                                                    {:class => have_states ? 'required' : 'hidden',
                                                     :disabled => !have_states}) +
                                bill_form.text_field(:state_name,
                                                     :class => !have_states ? 'required' : 'hidden',
                                                     :disabled => have_states)
                ].join.gsub('"', "'").gsub("\n", "")
                %>
                <%= javascript_tag do -%>
                    document.write("<%== state_elements %>");
                <% end -%>
              </p>
              <noscript>
                <%= bill_form.text_field :state_name, :class => 'required' %>
              </noscript>
          <% end %>

          <p class="field" id="bzipcode">
            <%= bill_form.label :zipcode, t(:zip) %><span class="required">*</span><br />
            <%= bill_form.text_field :zipcode, :class => 'required' %>
          </p>
          <p class="field" id="bphone">
            <%= bill_form.label :phone, t(:phone) %><span class="required">*</span><br />
            <%= bill_form.phone_field :phone, :class => 'required' %>
          </p>
          <% if Spree::Config[:alternative_billing_phone] %>
              <p class="field" id="baltphone">
                <%= bill_form.label :alternative_phone, t(:alternative_phone) %><br />
                <%= bill_form.phone_field :alternative_phone %>
              </p>
          <% end %>
        </div>
    <% end %>
  </fieldset>
</div>

<div class="columns omega six" data-hook="shipping_fieldset_wrapper">
  <fieldset id="shipping" data-hook>
    <%= form.fields_for :ship_address do |ship_form| %>
        <legend><%= t(:shipping_address) %></legend>
        <p class="field checkbox" data-hook="use_billing">
          <%= check_box_tag 'order[use_billing]', '1', (!(@order.bill_address.empty? && @order.ship_address.empty?) && @order.bill_address.same_as?(@order.ship_address)) %>
          <%= label_tag :order_use_billing, t(:use_billing_address), :id => 'use_billing' %>
        </p>
        <div class="inner" data-hook="shipping_inner">
          <p class="field" id="sfirstname">
            <%= ship_form.label :firstname, t(:first_name) %><span class="required">*</span><br />
            <%= ship_form.text_field :firstname, :class => 'required' %>
          </p>
          <p class="field" id="slastname">
            <%= ship_form.label :lastname, t(:last_name) %><span class="required">*</span><br />
            <%= ship_form.text_field :lastname, :class => 'required' %>
          </p>
          <% if Spree::Config[:company] %>
              <p class="field" id="scompany">
                <%= ship_form.label :company, t(:company) %><br />
                <%= ship_form.text_field :company %>
              </p>
          <% end %>
          <p class="field" id="saddress1">
            <%= ship_form.label :address1, t(:street_address) %><span class="required">*</span><br />
            <%= ship_form.text_field :address1, :class => 'required' %>
          </p>
          <p class="field" id="saddress2">
            <%= ship_form.label :address2, t(:street_address_2) %><br />
            <%= ship_form.text_field :address2 %>
          </p>

          <p class="field" id="scity">
            <%= ship_form.label :city, t(:city) %><span class="required">*</span><br />
            <%= ship_form.text_field :city, :class => 'required' %>
          </p>

          <p class="field" id="scountry">
            <%= ship_form.label :country_id, t(:country) %><span class="required">*</span><br />
        <span id="scountry">
          <%= ship_form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'required'} %>
        </span>
          </p>

          <% if Spree::Config[:address_requires_state] %>
              <p class="field" id="sstate">
                <% have_states = !@order.ship_address.country.states.empty? %>
                <%= ship_form.label :state, t(:state) %><span class="required">*</span><br />
                <% state_elements = [
                        ship_form.collection_select(:state_id, @order.ship_address.country.states,
                                                    :id, :name,
                                                    {:include_blank => true},
                                                    {:class => have_states ? 'required' : 'hidden',
                                                     :disabled => !have_states}) +
                                ship_form.text_field(:state_name,
                                                     :class => !have_states ? 'required' : 'hidden',
                                                     :disabled => have_states)
                ].join.gsub('"', "'").gsub("\n", "")
                %>
                <%= javascript_tag do -%>
                    document.write("<%== state_elements %>");
                <% end %>
              </p>
              <noscript>
                <%= ship_form.text_field :state_name, :class => 'required' %>
              </noscript>
          <% end %>

          <p class="field" id="szipcode">
            <%= ship_form.label :zipcode, t(:zip) %><span class="required">*</span><br />
            <%= ship_form.text_field :zipcode, :class => 'required' %>
          </p>
          <p class="field" id="sphone">
            <%= ship_form.label :phone, t(:phone) %><span class="required">*</span><br />
            <%= ship_form.phone_field :phone, :class => 'required' %>
          </p>
          <% if Spree::Config[:alternative_shipping_phone] %>
              <p class="field" id="saltphone">
                <%= ship_form.label :alternative_phone, t(:alternative_phone) %><br />
                <%= ship_form.phone_field :alternative_phone %>
              </p>
          <% end %>
        </div>
    <% end %>
  </fieldset>
</div>
<hr class="clear" />
<div class="form-buttons" data-hook="buttons">
  <%= submit_tag t(:save_and_continue), :class => 'continue button primary' %>
</div>

app/views/spree/checkout/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag states_url(:format => :js) %>
  <%= javascript_include_tag countries_url(:format => :js) %>
<% end %>

<div id="checkout" data-hook>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>

  <div class="row" data-hook="checkout_header">
    <h1 class="columns three alpha" data-hook="checkout_title"><%= t(:checkout) %></h1>
    <div class="columns thirteen omega" data-hook="checkout_progress"><%= checkout_progress %></div>
  </div>

  <div class="row" data-hook="checkout_content">
    <div class="columns <%= if @order.state != 'confirm' then 'alpha twelve' else 'alpha omega sixteen' end %>" data-hook="checkout_form_wrapper">
      <%= form_for @order, :url => update_checkout_path(@order.state), :html => { :id => "checkout_form_#{@order.state}" } do |form| %>
        <%= render @order.state, :form => form %>
      <% end %>
    </div>
    <% if @order.state != 'confirm' %>
      <div id="checkout-summary" data-hook="checkout_summary_box" class="columns omega four">
        <%= render :partial => 'summary', :locals => { :order => @order } %>
      </div>
    <% end %>
  </div>

</div>

app/views/spree/checkout/registration.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>
<div id="registration" data-hook>
  <div id="loginr" class="columns alpha eight">
    <%= render :file => 'spree/user_sessions/new', locals: {aux_links: false} %>
  </div>
  <div id="registrationus" class="columns alpha eight">
    <div id="new-customer" xmlns="http://www.w3.org/1999/html">
      <h4><%= t(:first_timer) %></h4>
      <span class="big_desc"><%= t(:reg_desc2) %></span>
      <%= form_tag seen_reg_page_path do %>
        <%= submit_tag t(:proceed_to_checkout), :class => 'button primary' %>
      <% end %>
    </div>
  </div>
</div>